### ISSUE TITLE
Feedback from Glenn Randle

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#39]
Anton,
Please make the following changes highlighted in this PDF
[PRRLA Design Comments9.21.pdf](https://github.com/pier2marketing/ucla-prrla/files/1325651/PRRLA.Design.Comments9.21.pdf)

-Saida

**Comment by rosalieucla** [comment]
Hi anton, 

From Glenn: 
Here is the link to DropBox with all the final files.

https://www.dropbox.com/s/w2qrejrt656bcr3/PRL%20final%20files.zip?dl=0


Here is the DropBox link to the logo file.

https://www.dropbox.com/s/2u19d2k72n9u4v5/PRL%20logo-01.png.zip?dl=0

thx, 
Rosalie

**Comment by Hlopec** [comment]
done

**Comment by markmatney** [comment]
Hi all,

We have received some more feedback and change requests. Please see the attached PDF for directions.
[PRRLA Design Comments 10-5.pdf](https://github.com/pier2marketing/ucla-prrla/files/1363738/PRRLA.Design.Comments.10-5.pdf)

**Comment by Hlopec** [comment]
done

**Comment by rosalieucla** [comment]
Please review again, it looks like these additional edits are still not done. 

thx!
Rosalie

**Comment by amereshchuk** [comment]
ignore 21px title, leave 24px.

**Comment by amereshchuk** [comment]
i just checked with dev, these edits was done yesterday and pushed to git.
right now edits are present on test env.
i assume that changes wasn't pulled to test env yesterday.

we will change title to 24px again.

please check again.

thank you.

**Comment by sjlargaespada** [comment]
Please slightly reduce the size of the "no thumbnail available" thumbnail. It is currently difficult to see a distinct separation between records.

<img width="1440" alt="screen shot 2017-10-11 at 9 12 26 am" src="https://user-images.githubusercontent.com/31044167/31452902-197e4e04-ae65-11e7-8e52-53c8fdde1b40.png">

**Comment by Hlopec** [comment]
done
