### ISSUE TITLE
Populate View Details Page metadata from solr document fields and not facets fields

### ISSUE THREAD

**Issue by pghorpade** [UCLALibrary/ucla-prrla#43]
Hi Anton,

For this page currently, the code uses the facet field data .
I have updated the wiki document [View Details Page](https://github.com/pier2marketing/ucla-prrla/wiki/Solr-4.10-Search-and-Browse-Specification#view-item-record) with examples of how to populate metadata from the solr document. 

let me know if you have questions

**Comment by amereshchuk** [comment]
hello, we have moved back all fields. before we had request to hide fields. please let me know if that works correct now. thank you.

**Comment by rosalieucla** [comment]
Hi!

The previous request was to hide field names when there was no values in them. .Where there is a value display all fields on 'view details' page

I can't qa the site now but will later this morning

Thx for all your fast work!!!!

Rosalie

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rosalieucla** [comment]
@amereshchuk, it would be great if you could fix this for us by Noon our time, tomorrow, 9/27.  

The details of the fields for the  view details is documented in Parinita's solr documentation on githhub. 

thx!
Rosalie

**Comment by pghorpade** [comment]
hi @amereshchuk ,

I tested a few records and all metadata is still missing on the View Details page.

View Details page should have any or all metadata in the solr document from json response returned ,

Here is the full list (This is documented in the github wiki https://github.com/pier2marketing/ucla-prrla/wiki/Solr-4.10-Search-and-Browse-Specification#view-item-record)

if any of  solr fields are missing for that item record, do not create labels and n/a values for it. Just skip it on the UI.



solr document fields | UI Elements Labels
-- | --
title_keyword | Title
creator_keyword | Author
subject_keyword | Subject 
description_keyword | Abstract
publisher_keyword | Publisher
contributor_keyword | Contributor
date_keyword | Date
type_keyword | Type
format_keyword | Format
identifier_keyword | Identifier,URL
source_keyword | Source
language_keyword | Language
relation_keyword | Relation
coverage_keyword | Coverage
rights_keyword | Rights
institutionName | Institution Name
collectionName | Collection Name

Say user clicks on view Item details link 
 http://test-prl.library.ucla.edu/detail/oai_3Alibrary.ucla.edu_3Asheetmusic_2FSX102871.xml


![screen shot 2017-09-26 at 5 43 26 pm](https://user-images.githubusercontent.com/4259468/30890573-8e5c74e6-a2e2-11e7-915c-423d0d3692c0.png)

raw solr query :
 http://test-solr.library.ucla.edu/solr/prrla/select?q=id%3Aoai_3Alibrary.ucla.edu_3Asheetmusic_2FSX102871.xml&wt=json&indent=true&fl=*_keyword,collectionName,institutionName

raw json respone
```
{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "q":"id:oai_3Alibrary.ucla.edu_3Asheetmusic_2FSX102871.xml",
      "indent":"true",
      "fl":"*_keyword,collectionName,institutionName",
      "wt":"json"}},
  "response":{"numFound":1,"start":0,"docs":[
      {
        "creator_keyword":["Bernstein, Elmer [composer]",
          "Sheldon, Ernie. [lyricist]"],
        "source_keyword":["SX102871"],
        "description_keyword":["Portraits of Kirk Douglas, Senta Berger, Frank Sinatra, Yul Brynner, and John Wayne on cover. ",
          "Moderately [tempo]",
          "E flat Major [key]"],
        "rights_keyword":["UCLA Library"],
        "collectionName":"Archive of Popular American Music ",
        "publisher_keyword":["New York : United Artists Music Co. Inc."],
        "institutionName":"University of California Los Angeles",
        "language_keyword":["English"],
        "subject_keyword":["Portraits",
          "Middle East"],
        "identifier_keyword":["http://digital.library.ucla.edu/apam/librarian?ITEMID=SX102871",
          "http://digital.library.ucla.edu/apam/librarian?ITEMID=SX102871"],
        "title_keyword":["Love me true",
          "Love me true, love sunshine love me rain, love me happy love me pain [first line]"]}]
  }}
```

**Remove following Labels from this page.**

_Alternate Title:
First Line:_

**The above raw json will look like following on  this Page:**

```
Title:           Love me true
                   Love me true, love sunshine love me rain, love me happy love me pain [first line]

External Link(s):   http://digital.library.ucla.edu/apam/librarian?ITEMID=SX102871
                            http://digital.library.ucla.edu/apam/librarian?ITEMID=SX102871   

Collection:       Archive of Popular American Music

Institution:       University of California Los Angeles

Author:           Bernstein, Elmer [composer]
                       Sheldon, Ernie. [lyricist]

Subject:     Portraits
                  Middle East

Source:     SX102871

Abstract:    Portraits of Kirk Douglas, Senta Berger, Frank Sinatra, Yul Brynner, and John Wayne on cover. 
                   Moderately [tempo]
                  E flat Major [key]

Rights:      UCLA Library

Publisher:   New York : United Artists Music Co. Inc.

Language:  English

Identifier:  http://digital.library.ucla.edu/apam/librarian?ITEMID=SX102871
                 http://digital.library.ucla.edu/apam/librarian?ITEMID=SX102871

```

let me know if you any questions.

**Comment by Hlopec** [comment]
done. please check it.

**Comment by pghorpade** [comment]
hi @amereshchuk ,

I still see no metadata for subject, relation, publisher, format, type on the view details page, for the following example

http://test-prl.library.ucla.edu/detail/oai_3Adtlappprd01.its.auckland.ac.nz_3A286347.xml

I am guessing for other data, there may be more fields missing on the UI.

Will update the ticket, as I find more.

**Comment by pghorpade** [comment]
I found another example

http://test-prl.library.ucla.edu/detail/oai:library.ucla.edu:digital2%2F21198-zz002bd3d8

subject, coverage, contributor fields are missing

the date value should be populated from date_identifier and not decade for this page.

**Comment by kjallen** [comment]
@Hlopec I think the general issue is on the display details page (example:
http://test-prl.library.ucla.edu/detail/oai:cuhk-dr:cuhk_957465
)
The fields that are being displayed are being sourced from the **facet** fields. They should be pulled from the solr document fields/oai-pmh dublin core fields. @pghorpade has listed the set above.

The mixup is most evident in the example above, the content that is being displayed for 'Date' on the UI is being sourced from the decade field, but should from the date_keyword field. This can be verified by viewing the source Solr query.

http://test-solr.library.ucla.edu/solr/prrla/select?q=id%3A%22oai%3Acuhk-dr%3Acuhk_957465%22&wt=json&indent=true

So all those fields that have *_keyword in the field name are dublin core fields and would be used rather than the facet fields.

**Comment by amereshchuk** [comment]
done. thank you for details. that was really helpful.

**Comment by amereshchuk** [comment]
http://test-solr.library.ucla.edu/solr/prrla/select?q=id:oai%5C:cuhk%5C-dr%5C:cuhk_957372&indent=true&wt=json&json.wrf=__ng_jsonp__.__req0.finished

date_keyword returns collection of strings, please let me know how to print date in this case? do we need to print them all or some of them of first one? please provide details which cover all cases?

right now we print all strings from date_keyword.

thank you,
Anton

**Comment by rosalieucla** [comment]
Yes, print them all, each date on its own line. 

thx!
Rosalie

**Comment by Hlopec** [comment]
done

**Comment by kjallen** [comment]
Confirmed, verified against http://test-prl.library.ucla.edu/detail/oai:cuhk-dr:cuhk_957465
