### ISSUE TITLE
Fix Decade filter

### ISSUE THREAD

**Issue by markmatney** [UCLALibrary/ucla-prrla#48]
There are two issues with the Decade filter (on the left hand side of the page at `/search`):
- Decades are sorted reverse-lexicographically, but should be sorted reverse-chronologically instead
- Years prior to year 0 are stored in Solr as a string of one or more digits preceded by a `-`, but should display with the suffix `B.C.E` instead of this prefix

A good example collection to see these issues is "United College Oracle Bones" from "CUHK Digital Repository".

One way to sort properly: map each string in the array of decades to an integer, sort the result reverse-numerically, map back to strings, then replace the `-` prefix with `B.C.E.` suffix.

**Comment by Hlopec** [comment]
done. added B.C.E. suffix.

**Comment by markmatney** [comment]
I ran the site locally in both Firefox 55 and Chromium 61 and I still see the `-` prefix (and no `B.C.E`).

I do see [the commit that purportedly fixes this](https://github.com/pier2marketing/ucla-prrla/commit/2dd16c8e7d24229214a3bbae8f5cb9f9da150de7). Please note that there should be no spaces in the suffix: should be `B.C.E.` exactly, not `B. C. E.`. Also, it looks like the value of the `humanName` property (which contains the suffixed string) may be unused by the UI.

**Comment by saslv** [comment]
@markmatney, thank you!
Fixed.

**Comment by markmatney** [comment]
Looks fine to me, thank you!
