### ISSUE TITLE
ng build with prod flag should use production solr

### ISSUE THREAD

**Issue by kjallen** [UCLALibrary/ucla-prrla#53]
If the build is done with the production flag, the url for the production solr should be used in solr queries

The url for the production solr instance is: solr.library.ucla.edu
The url for test solr instance is: test-solr.library.ucla.edu

**Comment by Hlopec** [comment]
done

**Comment by kjallen** [comment]
Thank you. Could clarifications of the changes or a way to confirm be provided? If I run:
ng build --env=prod --no-sourcemap

I am still seeing connections to test-solr.library.ucla.edu. The expected behavior would be solr.library.ucla.edu.

**Comment by amereshchuk** [comment]
could you please update code and try again?
we haven't done any changes here but just double checked, everything worked fine.

thank you.

**Comment by cachemeoutside** [comment]
Hello,

I'm not sure what's going on, but building with

ng build --env=prod --no-sourcemap

seems to have pushed an old build. Here's a test URL that I'm using:
http://test-prrla.library.ucla.edu/index

I've noticed that the header is different than what we build without the prod option(look at http://test-prl.library.ucla.edu)

Can you all look into this? Thanks.

**Comment by cachemeoutside** [comment]
Nevermind, it looks like it's working now. I copied to the wrong S3 bucket.

**Comment by cachemeoutside** [comment]
@kjallen can you review:
http://test-prrla.library.ucla.edu/index

it's built using the prod flag. you may want to have @markmatney upload one collection to test.

**Comment by markmatney** [comment]
indexing in progress and [collections are showing up](http://test-prrla.library.ucla.edu/explore-collections) -- that's a good sign I think

**Comment by cachemeoutside** [comment]
@kjallen I pushed latest prod code. I think this is OK to close, you'll want to confirm. Here's the URL:

http://demo-prl.library.ucla.edu/index

**Comment by kjallen** [comment]
Confirming correct behavior.
